### ISSUE TITLE
Question: Time needed to extract keys

### ISSUE THREAD

**Issue by 0000011111000000** [aczid/crypto1_bs#7]
Have you tested your code with the Infineon SLE-66 chipset?
What average time do you pull to extract both A and B keys from the card?

**Comment by aczid** [comment]
It depends so I don't know, and this is not really related to my work.

**Comment by 0000011111000000** [comment]
I will, I have one running atm.

What time did you pull on other cards you did try, days/weeks/months?

**Comment by aczid** [comment]
Other users have reported between 5 and 20 minutes of online (nonce-gathering) time, with negligible remaining offline (brute-force) time.

**Comment by aczid** [comment]
In my own tests I've noticed between 3 minutes and up to over 5 hours required for finding a key with the libnfc tool. One instance required over 200k nonces to get the complexity low enough. Sometimes, even at 95% probability, it doesn't find the key several times in a row. Eventually it finds everything, though. Be patient. :)

**Comment by amoeles** [comment]
In my case 4 minutes for finding a key with the libnfc tool.

Regards.

**Comment by amoeles** [comment]
Each block has his time, with the same tag blocks 0, 4 and 30 give me the keys a-b in 4-6 minutes but in block 36-b for example i wait 30-40 minutes, so in 21.000 nonces i decided to pulse enter to force brute crack and in 21% of progress i obtain the key :).

Thanks to aczid for active support.

**Comment by DrSchottky** [comment]
I planned to test crakcer performances on various archs: today I teted it on RPI3 (Raspbian, default clock, some extra compiler flags) and the speed is approx 34Mstates/sec.

**Comment by aczid** [comment]
Thanks for the benchmarks! I assume it works correctly on 32-bit machines now?

**Comment by DrSchottky** [comment]
Works like a charm! 
I'll test it on more archs next week.

**Comment by iceman1001** [comment]
How did you measure the performance in the solver @DrSchottky  ?

**Comment by aczid** [comment]
Because of the way work for the cracker is batched into buckets of uneven size, and these get scheduled over threads it's probably most fair to compare the cracker on its own by running it on only a single core at a time, searching the entire keyspace (by asking for a result that doesn't exist) and measuring the execution time.
The way I benchmark is:
`$ time ./solve_bs 0xcafec0de.txt 0`
With a version of `solve_bs.c` that I've patched to always run only 1 thread, then measure the execution wall time to measure the average number of threads/s.
